#pragma once

#include <cmath>

#define FLUID_HEIGHT 400
#define FLUID_WIDTH 1000
#define CELL_SIZE 1

#define PROJECTION_O 1.9
#define PROJECTION_N 10

#define FPS_AVG_SIZE 15

#define PHYSICS_G 0

#define PIPE_HEIGHT FLUID_HEIGHT / 3
#define PIPE_LENGTH 0
#define WIND_SPEED CELL_SIZE

#define CIRCLE_RADIUS FLUID_HEIGHT / 8.0
#define CIRCLE_POSITION_X FLUID_WIDTH / 2 + 40
#define CIRCLE_POSITION_Y FLUID_HEIGHT / 2
#define ENABLE_CIRCLE true

#define ARROW_HEAD_ANGLE M_PI / 8
#define ARROW_HEAD_LENGTH 6
#define ARROW_DISABLE_THRESH_HOLD -1
#define ARROW_LENGTH_MULTIPLIER 0.5
#define CENTER_ARROW_COLOR 0, 0, 0, 255
#define VERTICAL_EDGE_ARROW_COLOR 50, 255, 50, 255
#define HORIZONTAL_EDGE_ARROW_COLOR 50, 50, 255, 255
#define CORNER_ARROW_COLOR 50, 255, 255, 255
#define DRAW_CENTER_ARROW false
#define DRAW_VERTICAL_EDGE_ARROW false
#define DRAW_HORIZONTAL_EDGE_ARROW false
#define DRAW_CORNER_EDGE_ARROW false

#define D_T 10
#define USE_REAL_TIME false
#define REAL_TIME_MULTIPLIER 100