#pragma once

#include <cmath>

#define THREAD_COUNT 16

#define FLUID_HEIGHT 600
#define FLUID_WIDTH 1000
#define CELL_SIZE 1

#define PROJECTION_O 1.9
#define PROJECTION_N 50

#define FPS_AVG_SIZE 200

#define PHYSICS_G 0

#define PIPE_HEIGHT FLUID_HEIGHT / 4
#define PIPE_LENGTH 0
#define SMOKE_LENGTH 10
#define WIND_SPEED 200
#define WIND_SMOKE 1

#define ENABLE_RIGHT_WALL false

#define CIRCLE_RADIUS FLUID_HEIGHT / 30.0
#define CIRCLE_POSITION_X FLUID_WIDTH / 2 + 40
#define CIRCLE_POSITION_Y FLUID_HEIGHT / 2
#define ENABLE_CIRCLE true

#define ARROW_SPACER 20
#define ARROW_HEAD_ANGLE M_PI / 8
#define ARROW_HEAD_LENGTH 5
#define ARROW_DISABLE_THRESH_HOLD -1
#define ARROW_LENGTH_MULTIPLIER 0.1
#define CENTER_ARROW_COLOR 0, 0, 0, 255
#define VERTICAL_EDGE_ARROW_COLOR 50, 255, 50, 255
#define HORIZONTAL_EDGE_ARROW_COLOR 50, 50, 255, 255
#define CORNER_ARROW_COLOR 50, 255, 255, 255
#define DRAW_CENTER_ARROW false
#define DRAW_VERTICAL_EDGE_ARROW false
#define DRAW_HORIZONTAL_EDGE_ARROW false
#define DRAW_CORNER_ARROW false

#define D_T 0.05
#define USE_REAL_TIME false
#define REAL_TIME_MULTIPLIER 1

#define SMOKE_DECAY_RATE 0.05

#define REPORT_FILE_NAME "report.log"
#define ALLOW_LOG_ON_RELEASE true
#define FPS_LOG_SPACER 1

#define TRACE_LENGTH 50
#define TRACE_SPACER 40
#define ENABLE_TRACES false

#define ENABLE_PRESSURE true
#define ENABLE_SMOKE true
#define FLUID_DENSITY 1